# Generated by Django 4.1.6 on 2023-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shope", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=300)),
                ("nom", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=200)),
                ("pays", models.CharField(max_length=100)),
                ("zipecode", models.CharField(max_length=200)),
                ("date_commande", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-date_commande",),
            },
        ),
    ]
